/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.bookstore;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.bookstore.MessageUtils.getMessage;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.example.bookstore.util.Model;
import org.example.bookstore.util.DB;
import org.example.bookstore.controllers.Home;

public class App {
    public static void main(String[] args) {
        // try {

            // DB db = new DB();

            // Create an instance of the DB class
            Home home = new Home();
            
            // // Fetch data using the query builder
            // List<Map<String, Object>> results = db.table("users")
            // .select("id", "name")
            // .where("status", "active", "=")
            // .orderBy("name", "ASC")
            // .limit(5)
            // .get();

            // Print out the results
            // for (Map<String, Object> row : results) {
            //     System.out.println(row);
            // }
        // } catch (SQLException e) {
        //     e.printStackTrace();
        // }
    }
}

